name: Start first workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "welcome to our first GitHub Actions Workfolw :)"

      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: List repo files
        run: ls -la
